apiVersion: v1
kind: Pod
metadata:
  name: "webserver"
  namespace: default
  labels:
    app: "webserver"
spec:
  containers:
  - name: webserver
    image: "nginx"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
  restartPolicy: Always