apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: medium-priority
value: 700
globalDefault: false
description: "This is a medium priority class. Use it for regular applications."
