apiVersion: v1
kind: Pod
metadata:
  name: "myapp"
  namespace: taints
spec:
  containers:
  - name: myapp
    image: "nginx"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
      - containerPort: 80
  restartPolicy: Always
