apiVersion: v1
kind: Pod
metadata:
  name: "nginx200"
  namespace: configmaps
spec:
  containers:
  - name: nginx200
    image: "ubuntu:latest"
    command: ["sleep", "5"]
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: db_host
      valueFrom:
        configMapKeyRef:
          name: myapp
          key: db_01
          optional: true
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always