apiVersion: v1
kind: Service
metadata:
  name: webappvc
  namespace: rollingout
spec:
  selector:
    appversion: v2
    # appname: okanwebapp
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80