apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-policy
  namespace: database
spec:
  podSelector:
    matchLabels:
      type: database
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              type: myapi
      ports:
      - port:  3306
        protocol: TCP