apiVersion: v1
kind: Pod
metadata:
  name: "myapp"
  namespace: initcontainers
spec:
  initContainers:
    - name: myapp2
      image:  ubuntu:latest
      command: ["printenv"]
      args: ["HOSTNAME"]
    - name: myapp3
      image: ubuntu:latest
      command: ["printenv"]
      args: ["KUBERNETES_PORT"]
  containers:
  - name: myapp
    image: "nginx"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
  restartPolicy: Always