apiVersion: v1
kind: Pod
metadata:
  name: "nginx100"
  namespace: nginx100
spec:
  containers:
  - name: webserver
    image: "nginx:1.25-alpine"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always