apiVersion: v1
kind: Pod
metadata:
  name: "test-logger"
  namespace: multi-container
  labels:
    app: "test-logger"
spec:
  containers:
  - name: my-test-logger
    image: "0kanh0llander/test-logger:v1"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
  restartPolicy: Always