apiVersion: v1
kind: Pod
metadata:
  name: "startup-pod"
  namespace: probes
spec:
  containers:
    - name: mysql
      image: "mysql:latest"
      resources:
        limits:
          cpu: 600m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: abc123
      ports:
        - name: liveness-port
          containerPort: 3306
      livenessProbe:
        tcpSocket:
          port: liveness-port
        failureThreshold: 8
        periodSeconds: 5
  restartPolicy: Always