apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: qos
  labels:
    app: myapp
spec:
  containers:
  - name: database
    image: "mysql:latest"
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
    ports:
    - containerPort:  3306
  restartPolicy: Always