apiVersion: apps/v1
kind: Deployment
metadata:
  name:  okanwebappv1
  namespace: rollingout
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: okanwebapp
  template:
    metadata:
      labels:
        appname: okanwebapp
        appversion: v1
    spec:
      containers:
      - name:  okanwebapp
        image:  0kanh0llander/rollingupdatewebapp:v1
        resources:
          requests:
            cpu: 300m
            memory: 150Mi
          limits:
            cpu: 300m
            memory: 150Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  80
      restartPolicy: Always